"""
Signal 2 - LLM classifier (semantic), via Groq (llama-3.3-70b-versatile).

Asks a large model for a holistic probability that the text was AI-generated. Captures
the semantic/stylistic gestalt that stylometry cannot see (planning.md sec.2).

Output shape (matches planning.md sec.2):
    { "p_ai": float in [0,1] | None,
      "rationale": str,
      "available": bool }          # False on any Groq error/timeout -> pipeline degrades

Blind spots: it is another AI judging AI (uncalibrated, can be confidently wrong),
non-deterministic, and prone to false positives on polished / non-native-English human
writing. That is why it is fused with an independent structural signal, not trusted alone.
"""

import json
import os

MODEL = "llama-3.3-70b-versatile"
TIMEOUT_SECONDS = 20

_SYSTEM = (
    "You are a forensic text analyst. Estimate the probability that a passage was "
    "generated by an AI language model rather than written by a human. Consider "
    "semantic and stylistic cues: generic or hedged phrasing, unnatural smoothness, "
    "lack of specific lived detail, and predictable structure suggest AI; idiosyncratic "
    "voice, concrete specifics, and natural irregularity suggest a human. Be calibrated: "
    "reserve probabilities near 0 or 1 for clear cases, and use mid-range values when "
    "genuinely unsure. Respond with ONLY compact JSON of the form "
    '{"p_ai": <number 0..1>, "rationale": "<one short sentence>"}.'
)


def _clamp01(x):
    try:
        return max(0.0, min(1.0, float(x)))
    except (TypeError, ValueError):
        return None


def analyze(text, client=None):
    """Return the LLM signal for `text`. Pass a Groq client for testing/reuse; otherwise
    one is constructed from GROQ_API_KEY. Never raises - failures return available=False."""
    text = (text or "").strip()
    if not text:
        return {"p_ai": None, "rationale": "empty text", "available": False}

    try:
        if client is None:
            from groq import Groq

            api_key = os.environ.get("GROQ_API_KEY")
            if not api_key:
                return {
                    "p_ai": None,
                    "rationale": "no GROQ_API_KEY configured",
                    "available": False,
                }
            client = Groq(api_key=api_key, timeout=TIMEOUT_SECONDS)

        resp = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": f"Passage:\n\n{text}"},
            ],
            temperature=0.2,
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        raw = resp.choices[0].message.content
        parsed = json.loads(raw)
        p_ai = _clamp01(parsed.get("p_ai"))
        if p_ai is None:
            return {
                "p_ai": None,
                "rationale": f"unparseable model output: {raw[:120]}",
                "available": False,
            }
        return {
            "p_ai": round(p_ai, 4),
            "rationale": str(parsed.get("rationale", ""))[:300],
            "available": True,
        }
    except Exception as exc:  # network error, bad key, rate limit, JSON error...
        return {
            "p_ai": None,
            "rationale": f"llm signal unavailable: {type(exc).__name__}: {exc}"[:200],
            "available": False,
        }


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    tests = {
        "clearly AI (formal essay)": (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, it "
            "is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        ),
        "clearly human (casual)": (
            "ok so i finally tried that new ramen place downtown and honestly? underwhelming. "
            "the broth was fine but they put WAY too much sodium in it and i was thirsty for "
            "like three hours after. my friend got the spicy version and said it was better. "
            "probably won't go back unless someone drags me there"
        ),
    }
    for name, txt in tests.items():
        r = analyze(txt)
        print(f"\n[{name}] available={r['available']}")
        print(f"  p_ai={r['p_ai']}")
        print(f"  rationale={r['rationale']}")
